name: Test
on:
  workflow_call:

jobs:
  test:
    name: Create test site
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [ '3.3', '3.4', '4.0' ]

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0 # middleman init wants to clone the repo, so we need full history

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: '.nvmrc'

      - uses: ruby/setup-ruby@003a5c4d8d6321bd302e38f6f0ec593f77f06600 # v1.319.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run tests
        run: ./create-test-site.sh
