name: Test

on: [push, pull_request]

jobs:
  test:
    name: Create test site
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [ '3.3', '3.4', '4.0' ]

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0 # middleman init wants to clone the repo, so we need full history

      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run tests
        run: ./create-test-site.sh
